In [27]:
import numpy as np

x = np.array( [[800,2], [1000,3], [1200,3], [1500,4] , [1800,4]])
# rooms = np.array([2, 3, 3, 4 , 4])
# x = np.column_stack((area, rooms))
# Column stack area and room together into a 2d array
print("x = " + str(x))
#Price = y
y = np.array([40,55,65,80,95])
print("y = " + str(y))


x = [[ 800    2]
 [1000    3]
 [1200    3]
 [1500    4]
 [1800    4]]
y = [40 55 65 80 95]


In [28]:
x_mean = np.mean(x, axis=0)
x_std = np.std(x, axis=0)
x_norm = (x - x_mean) / x_std

one_array = np.ones((x_norm.shape[0]))
X_b = np.c_[(one_array, x_norm)]

print("Normalized x = " + str(X_b))

Normalized x = [[ 1.         -1.29385109 -1.60356745]
 [ 1.         -0.73130714 -0.26726124]
 [ 1.         -0.16876319 -0.26726124]
 [ 1.          0.67505274  1.06904497]
 [ 1.          1.51886867  1.06904497]]


In [29]:
b_cap = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
#.dot is same as @ operator
print("Estimated coefficients = :" + str(b_cap))

Estimated coefficients = :[67.         16.24394152  3.03203271]
